services:
  piru-watcher:
    build: .
    container_name: piru-watcher

    stdin_open: true
    tty: true

    volumes:
      - ./piru_storage.json:/app/piru_storage.json
      - ./data/runbooks:/app/data/runbooks
